[build]
  command = "npm run build"
  publish = "out"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/pages/kontakt.html"
  to = "/kontakt"
  status = 301

[[redirects]]
  from = "/pages/produkty-sluzby.html"
  to = "/produkty-sluzby"
  status = 301

[[redirects]]
  from = "/pages/referencie.html"
  to = "/referencie"
  status = 301

[[redirects]]
  from = "/contact-form.php"
  to = "/kontakt"
  status = 301
